### ISSUE TITLE
Error on Debian 12, Gnome 43.6

### ISSUE THREAD

**Issue by redscorpse** [tuberry/light-dict#26] opened 2023-09-23 16:38 UTC
The settings of extension light-dict@tuberry.github.io had an error:
```
TypeError: method Gtk.CssProvider.load_from_data: At least 2 arguments required, but only 1 passed
```

Stack trace:
```
fillPreferencesWindow@/home/reds/.local/share/gnome-shell/extensions/light-dict@tuberry.github.io/prefs.js:29:14
_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
async*LaunchExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:110:14
_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
_wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

**Comment by tuberry** [comment] 2023-09-24 03:05
Duplicate of #23. Please install from Github to fix:
```bash
git clone --recurse-submodules https://github.com/tuberry/light-dict.git && cd light-dict
git checkout 16c9702 && meson setup build && meson install -C build
```

**Closed as completed by tuberry** 2023-09-24 03:05 UTC
